import { NextPage } from "next/types";
import Head from 'next/head' 
import styles from '../styles/Home.module.css'
import { Container, Grid, Tab, Tabs,Box } from '@mui/material'
import {useEffect, useState} from 'react'
import { HeadingProp } from "./../component/HeadingProp";
import DocumentCreation from './documentCreation';
import DocumentRead from './documentRead';
import { checkWallet} from './../component/web3walletcheck';



const Home: NextPage = () =>{

    const [selectedTab, setSelectedTab] = useState(0);
    const [currentAccount, setCurrentAccount] = useState(null);
    

   let checkWalletAndInit = () =>{
     setCurrentAccount(checkWallet(window));
   }

    useEffect(() => {
                      checkWalletAndInit();
                    }, [])

    return (
        <div className={styles.container}>
          <Head>
            <title>Document Contract Demo</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
        
        <Container component="main" maxWidth="lg" style={{ background: '#E5E5E5' }}>
             
            <Grid container>
              <HeadingProp/>
            </Grid>  
            <Box
                width={1150} sx={{ display: 'flex', flexgrow:'1', bgcolor: 'background.paper', height: 720 }}
            >
            <Tabs orientation="vertical" value={selectedTab} onChange={(e,val) => setSelectedTab(val)} variant='fullWidth'>
              
                  <Tab label="Document Creation"/>
    
                  <Tab label="Document Read"/>
                  
    
                </Tabs>
                {selectedTab ===0 && <DocumentCreation/>}
                {selectedTab ===1 && <DocumentRead/>}
 
            </Box>    
     
          </Container>
    
        </div>
      )
    }
    
export default Home
    
