version: '2'

services:
  ipfsnodeserver:
    container_name: ipfsnodeserver
    image: genera.ipfsnodeserver:latest
    network_mode: "host"
    ports:
     - 3100:3100
# Option to be used for linux when communicating with host network
#    extra_hosts:
#     - "host.docker.internal:host-gateway" 
